//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSC_Report3
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSC_Record
    {
        public string seatNo { get; set; }
        public string FirstName { get; set; }
        public string LasttName { get; set; }
        public Nullable<float> Math { get; set; }
        public Nullable<float> English { get; set; }
        public Nullable<float> Physics { get; set; }
        public Nullable<float> Chemistry { get; set; }
        public Nullable<float> Computer { get; set; }
    }
}
